/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realtimesys.view;

import realtimesys.model.PeriodicTask;
import realtimesys.presenter.ShortViewPresenter;

/**
 *
 * @author namng
 */
public class TaskInfoShortViewWithEdit extends javax.swing.JPanel {

    private ShortViewPresenter presenter;

    /**
     * Get the value of presenter
     *
     * @return the value of presenter
     */
    public ShortViewPresenter getPresenter() {
        return presenter;
    }

    /**
     * Set the value of presenter
     *
     * @param presenter new value of presenter
     */
    public void setPresenter(ShortViewPresenter presenter) {
        this.presenter = presenter;
    }

    /**
     * Creates new form TaskInfoShortViewWithEdit
     */
    public TaskInfoShortViewWithEdit() {
        initComponents();
    }

    /**
     * Get the value of taskInfo
     *
     * @return the value of taskInfo
     */
    public PeriodicTask getTaskInfo() {
        return shortView.getTaskInfo();
    }

    /**
     * Set the value of taskInfo
     *
     * @param taskInfo new value of taskInfo
     */
    public void setTaskInfo(PeriodicTask taskInfo) {
        this.shortView.setTaskInfo(taskInfo);
    }
    private boolean excludeFromSchedule;

    /**
     * Get the value of excludeFromSchedule
     *
     * @return the value of excludeFromSchedule
     */
    public boolean isExcludeFromSchedule() {
        return this.excludeCheckBox.isSelected();
    }

    /**
     * Set the value of excludeFromSchedule
     *
     * @param excludeFromSchedule new value of excludeFromSchedule
     */
    public void setExcludeFromSchedule(boolean excludeFromSchedule) {
        this.excludeCheckBox.setSelected(excludeFromSchedule);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shortView = new realtimesys.view.TaskInfoShortView();
        excludeCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(shortView, java.awt.BorderLayout.CENTER);

        excludeCheckBox.setText("Exclude from schedule");
        add(excludeCheckBox, java.awt.BorderLayout.PAGE_END);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(presenter != null){
            presenter.Delete(shortView.getTaskInfo());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(presenter != null){
            presenter.Edit(shortView.getTaskInfo());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox excludeCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private realtimesys.view.TaskInfoShortView shortView;
    // End of variables declaration//GEN-END:variables
}
