/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realtimesys.view;
import java.awt.Graphics;
import realtimesys.model.PeriodicTask;
import realtimesys.model.Task;

/**
 *
 * @author namng
 */
public class TaskInfoView extends javax.swing.JPanel {

    /**
     * Creates new form TaskInfoView
     */
    public TaskInfoView() {
        initComponents();
    }

    private PeriodicTask taskInfo;

    /**
     * Get the value of taskInfo
     *
     * @return the value of taskInfo
     */
    public PeriodicTask getTaskInfo() {
        if(this.taskInfo != null){
            taskInfo.setName(nameTextBox.getText());
            taskInfo.setExeTime(Double.valueOf(eTimeTextBox.getText()));
            taskInfo.setPeriod(Double.valueOf(periodicTextBox.getText()));
            taskInfo.setPhase(Double.valueOf(phaseTextBox.getText()));
            taskInfo.setRDeadline(Double.valueOf(rDeadlineTextBox.getText()));
            return taskInfo;
        }
        else{
            taskInfo = new PeriodicTask();
            taskInfo.setName(nameTextBox.getText());
            taskInfo.setExeTime(Double.valueOf(eTimeTextBox.getText()));
            taskInfo.setPeriod(Double.valueOf(periodicTextBox.getText()));
            taskInfo.setPhase(Double.valueOf(phaseTextBox.getText()));
            taskInfo.setRDeadline(Double.valueOf(rDeadlineTextBox.getText()));
            setTaskInfo(taskInfo);
            return taskInfo;
        }
    }
    
    @Override
    protected void paintComponent(Graphics g)
    {
        if(taskInfo == null){
            idTextBox.setText(String.valueOf(Task.getCnt()));
        }
    }

    /**
     * Set the value of taskInfo
     *
     * @param taskInfo new value of taskInfo
     */
    public void setTaskInfo(PeriodicTask taskInfo) {
        idTextBox.setText(String.valueOf(taskInfo.getId()));
        nameTextBox.setText(String.valueOf(taskInfo.getName()));
        periodicTextBox.setText(String.valueOf(taskInfo.getPeriod()));
        phaseTextBox.setText(String.valueOf(taskInfo.getPhase()));
        rDeadlineTextBox.setText(String.valueOf(taskInfo.getRDeadline()));
        eTimeTextBox.setText(String.valueOf(taskInfo.getExeTime()));
        this.taskInfo = taskInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idTextBox = new javax.swing.JTextField();
        nameTextBox = new javax.swing.JTextField();
        periodicTextBox = new javax.swing.JTextField();
        eTimeTextBox = new javax.swing.JTextField();
        rDeadlineTextBox = new javax.swing.JTextField();
        phaseTextBox = new javax.swing.JTextField();

        jLabel1.setText("Task id:");

        jLabel2.setText("Task name:");

        jLabel3.setText("Periodic:");

        jLabel4.setText("exe time:");

        jLabel5.setText("Relative deadline:");

        jLabel6.setText("Phase:");

        idTextBox.setEditable(false);
        idTextBox.setName("idTextBox"); // NOI18N

        nameTextBox.setName("nameTextBox"); // NOI18N

        periodicTextBox.setName("periodicTextBox"); // NOI18N

        eTimeTextBox.setName("exeTimeTextBox"); // NOI18N

        rDeadlineTextBox.setName("rDeadlineTextBox"); // NOI18N

        phaseTextBox.setName("phaseTextBox"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phaseTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rDeadlineTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eTimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodicTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {eTimeTextBox, idTextBox, nameTextBox, periodicTextBox, phaseTextBox, rDeadlineTextBox});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(periodicTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eTimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rDeadlineTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phaseTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {eTimeTextBox, idTextBox, nameTextBox, periodicTextBox, phaseTextBox, rDeadlineTextBox});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eTimeTextBox;
    private javax.swing.JTextField idTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameTextBox;
    private javax.swing.JTextField periodicTextBox;
    private javax.swing.JTextField phaseTextBox;
    private javax.swing.JTextField rDeadlineTextBox;
    // End of variables declaration//GEN-END:variables
}
